<?php

/**
 * Constants.php
 *
 * Define all accessible API Keys for agencies that require key.
 */

define("CENSUS_BASE_URL", "api.census.gov");
define("BUSUSA_BASE_URL", "business.usa.gov");
define("NOAA_BASE_URL", "ncdc.noaa.gov");

//Define API Keys
define("CENSUS_BUREAU_KEY", "10101010101010"); // Replace the "0101010" with a registered API Key
define("DOL_KEY", "10101010101010"); // Replace the "0101010" with a registered API Key
define("NOAA_KEY", "10101010101010"); // Replace the "0101010" with a registered API Key
